version: '3.8'

services:            
  db:
    image: postgres:14.1-alpine
    networks:
      - gateway
    restart: always
    user: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data  
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
  
  db-test:
    image: postgres:14.1-alpine
    restart: always
    user: postgres
    networks:
      - gateway
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5430:5432'
    volumes:
      - db:/var/lib/postgresql/dataTest   
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
      
  app:
    networks:
      - gateway
    environment:
      - SPRING.DATASOURCE.URL=jdbc:postgresql://db:5432/postgres
      - IP_DB=db
      - IP_DB_TEST=db-test
    depends_on:
      - db
      - db-test
    build: .
    restart: on-failure
    ports:
      - '8080:8080'
    depends_on:
        db:
            condition: service_healthy
        db-test:
            condition: service_healthy

volumes:
  db:
    driver: local
    
networks:
    gateway: {}
